spring:
  datasource:
    url: jdbc:mysql://localhost:3306/automobili
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: toor

  #tab opzionali
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: true