#tag obbligatori
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/automobili
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:h2:mem:automobili
    #driver-class-name: org.h2.Driver
    username: root
    password: toor

#tab opzionali
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /console/h2
  web:
    error:
      include-message: always
      include-path: always
      include-binding-errors: always
      include-stacktrace: always

jwt:
  secret: MiaChiaveAbbastanzaLungaPerGestireLaSicurezzaDelTokenJWT
  expiration: 3600000