#tag obbligatori
spring:
  web:
    error:
      include-message: always
      include-path: always
      include-binding-errors: always
      include-stacktrace: always
  profiles:
    active: h2

jwt:
  secret: MiaChiaveAbbastanzaLungaPerGestireLaSicurezzaDelTokenJWT
  expiration: 3600000
